// ==UserScript==
// @name         MyManager All-in-One Suite
// @namespace    http://tampermonkey.net/
// @version      121
// @description  An all-in-one suite for mymanager.gr. Auto-updates from GitHub — install this file once.
// @author       Gkorogias
// @match        *://thefixers.mymanager.gr/*
// @run-at       document-start
// @grant        GM_addStyle
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_xmlhttpRequest
// @updateURL    https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_loader.user.js
// @downloadURL  https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_loader.user.js
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_themes.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_config.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_utils.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_print.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_styles.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_settings.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_search.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_scratchpad.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_mascot.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_gamification.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_phonelist.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_technicianstats.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_orderhistory.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_status40.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_pricetransfer.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_statushover.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_orderlink.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_weather.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_eod.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_repair_reminders.js?v=121
// @require      https://raw.githubusercontent.com/Gkorogias/MANAGER/main/myman_allinone.js?v=121
// @connect      thefixers.mymanager.gr
// @connect      geocoding-api.open-meteo.com
// @connect      api.open-meteo.com
// @connect      raw.githubusercontent.com
// ==/UserScript==

// Auto-generated by scripts/generate-loader.mjs — do not edit by hand.
