/**
 * Regenerates myman_loader.user.js and syncs SCRIPT_META.version in myman_config.js
 * from myman_manifest.json. Run after bumping the manifest version:
 *
 *   node scripts/generate-loader.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'myman_manifest.json'), 'utf8'));
const { version, updateBase, modules } = manifest;
const loaderUrl = `${updateBase}/myman_loader.user.js`;

const requireLines = modules
    .map((file) => `// @require      ${updateBase}/${file}`)
    .concat(`// @require      ${updateBase}/myman_allinone.js`)
    .join('\n');

const loader = `// ==UserScript==
// @name         ${manifest.name}
// @namespace    http://tampermonkey.net/
// @version      ${version}
// @description  An all-in-one suite for mymanager.gr. Auto-updates from GitHub — install this file once.
// @author       Gkorogias
// @match        *://thefixers.mymanager.gr/*
// @run-at       document-start
// @grant        GM_addStyle
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_listValues
// @grant        GM_xmlhttpRequest
// @updateURL    ${loaderUrl}
// @downloadURL  ${loaderUrl}
${requireLines}
// @connect      thefixers.mymanager.gr
// @connect      geocoding-api.open-meteo.com
// @connect      api.open-meteo.com
// @connect      raw.githubusercontent.com
// ==/UserScript==

// Auto-generated by scripts/generate-loader.mjs — do not edit by hand.
`;

fs.writeFileSync(path.join(root, 'myman_loader.user.js'), loader);

const configPath = path.join(root, 'myman_config.js');
let config = fs.readFileSync(configPath, 'utf8');
const metaBlock = `const SCRIPT_META = {
        version: '${version}',
        updateBase: '${updateBase}',
        manifestUrl: '${updateBase}/myman_manifest.json',
        loaderUrl: '${loaderUrl}'
    };`;

if (config.includes('const SCRIPT_META = {')) {
    config = config.replace(/const SCRIPT_META = \{[\s\S]*?\};/, metaBlock);
} else {
    config = config.replace(
        /(const STORAGE_KEYS = \{)/,
        `${metaBlock}\n\n    $1`
    );
}

fs.writeFileSync(configPath, config);
console.log(`Generated myman_loader.user.js and synced SCRIPT_META.version = ${version}`);
